---
spring:
  application:
    name: "bomple"
  datasource:
    url: "jdbc:mysql://prod-url:3310/bosch_db"
    username: "root"
    password: ""
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  liquibase:
    enabled: true
    drop-first: true
    change-log: "classpath:db/changelog/init_master.yml"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
